### ISSUE TITLE
Sending JPEG 2000 compressed images fails

### ISSUE THREAD

**Issue by efflicto** [scaramallion/pynetdicom#40] opened 2016-04-19 11:10 UTC
Traceback:

> Traceback (most recent call last):                                                                                                        
  File "storescu.py", line 136, in <module>                                                                                               
    status = assoc.send_c_store(dataset)                                                                                                  
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pynetdicom-0.9.0-py3.5.egg\pynetdicom\association.py", line 688, in send_c_st
ore                                                                                                                                       
    dataset = correct_ambiguous_vr(dataset, transfer_syntax)                                                                              
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pynetdicom-0.9.0-py3.5.egg\pynetdicom\utils.py", line 43, in correct_ambiguou
s_vr                                                                                                                                      
    for elem in dataset:                                                                                                                  
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pydicom\dataset.py", line 367, in __iter__                                   
    yield self[tag]                                                                                                                       
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pydicom\dataset.py", line 319, in __getitem__                                
    self[tag].value = self.pixel_array                                                                                                    
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pydicom\dataset.py", line 514, in pixel_array                                
    return self._get_pixel_array()                                                                                                        
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pydicom\dataset.py", line 507, in _get_pixel_array                           
    self._pixel_array = self._pixel_data_numpy()                                                                                          
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pydicom\dataset.py", line 397, in _pixel_data_numpy                          
    raise NotImplementedError("Pixel Data is compressed in a format pydicom does not yet handle. Cannot return array. Pydicom might be abl
e to convert the pixel data using GDCM if it is installed.")                                                                              
NotImplementedError: Pixel Data is compressed in a format pydicom does not yet handle. Cannot return array. Pydicom might be able to conve
rt the pixel data using GDCM if it is installed.    

Reading the file via pydicom works fine. Is there a quick solution? I just want to send the images as I get them.

**Comment by scaramallion** [comment] 2016-04-20 00:38
This seems to be related to my poor attempt at determining ambgiuous VR when using Implicit VR. The quickest option may be to simply try using one of the explicit VR transfer syntaxes (`-xe` or `-xb` in `storescu.py`), but I'm not having any luck finding a suitable dataset to test this suggestion with.

It'd help a lot if you could attach an anonymised file for me to test with. In the meantime I've added a workaround if you want to test that.

**Comment by efflicto** [comment] 2016-04-20 09:04
Thanks for your help. I'll test the workaround and let you know.
Here are some test images. If you need more, let me know!

https://dl.0x05.de/E0014540.ZIP

**Comment by scaramallion** [comment] 2016-04-21 01:53
Thanks for the files, they helped a lot. The AttributeError from the missing 'keyword' is because you're not using the most recent update to pydicom that added it (https://github.com/darcymason/pydicom/commit/3d12f8df987ca57c3581d80ef24cd30a141ffef8). This should hopefully also address the original exception that you had as I can't reproduce that on my end.

However, because the dataset's transfer syntax is JPEG2000LosslessOnly and pydicom can't handle compressed pixel data, when pydicom is used to encode the dataset (during `Association.send_c_store`) in the correct transfer syntax as negotiated during association,  it fails when it tries to encode the pixel data. Testing bears this out as the dataset will send fine up until the PixelData which doesn't get converted. Unfortunately this isn't something I can fix, except by notifying the user that sending compressed images isn't supported.

I'd suggest using DCMTK's [dcmdjpeg](http://support.dcmtk.org/docs/dcmdjpeg.html) to decompress the datasets before sending (if you're using python then the `subprocess` module can be used to call it). Alternatively if you have control over the SCP as well you could try DCMTK's storescu with -xv and storescp with +xv.

Sorry I can't be of further help.

**Comment by efflicto** [comment] 2016-04-21 11:53
Thanks four your help!
I mixed up pydicom with pynetdicom while installing the new version sorry.

I'm using the scp from pynetdicom to get the images. Generally my workflow should be like that:
Sender -> Receiver -> Database lookup for correct patient informations -> corrections -> send to another destination.
I'll give DCMTK a shot for conversion. Thank you!

**Comment by efflicto** [comment] 2016-04-21 12:19
I think that now, all images get set as unsupported compressed images. Maybe im wrong but I get this:

> $ py -3 storescu.py localhost 105 "C:\prog\PyDicomServer\testing\images\E0014544\I0410689.dcm"
W: Unable to send the dataset due to pydicom not supporting compressed datasets
E: Sending file failed

Here is the image I tried: https://dl.0x05.de/I0410689.zip

**Comment by scaramallion** [comment] 2016-04-22 02:48
Yeah, I had the test for uncompressed syntax backwards. It should be fixed in the dev branch now.

The Transfer Syntax for that dataset is 1.2.840.10008.1.2.4.90 which is 'JPEG 2000 Image Compression (Lossless Only)' which is also a compressed syntax. Not only that, but it looks like that syntax isn't supported by dcmdjpeg either unfortunately.

Datasets with the following transfer syntaxes are supported by storescp.py and storescu.py:
```
1.2.840.10008.1.2            Implicit VR Little Endian
1.2.840.10008.1.2.1          Explicit VR Little Endian
1.2.840.10008.1.2.1.99       Deflated Explicit VR Little Endian
1.2.840.10008.1.2.2          Explicit VR Big Endian
```

Thanks for the offer, I'm a bit busy with other stuff at the moment but if I need someone to help test I'll let you know.

**Comment by efflicto** [comment] 2016-04-22 08:11
It'f fixed, thank you!
Luckily the JPEG compressed images are rare. I just catch it as exception and everything is good.
Thank you very much for your help!

**Closed** 2016-04-25 12:17 UTC
Labels: bug
